wandb_project: wv_linear_sm_num
wandb_group: align=0.82_p=0.25_filtered
train_triplets: ../datasets/wv_linear_sm_triplets/align=0.82_num/0.25/train_triplets_filtered.pkl
valid_triplets: ../datasets/wv_linear_sm_triplets/align=0.82_num/0.25/valid_triplets_filtered.pkl
test_triplets: ../datasets/wv_linear_sm_triplets/align=0.82_num/0.25/test_triplets_filtered.pkl
weights:
- 0
- 1
- 1
- 1
powers:
- 2
- 2
filtered: true
model: MTL_slow
