wandb_project: wv_squarelin_noisy
wandb_group: align=0.84_p=0.4_filtered
train_triplets: ../data/datasets/wv_squarelin/triplets/align=0.84_noisy/0.4/train_triplets_filtered.pkl
valid_triplets: ../data/datasets/wv_squarelin/triplets/align=0.84_noisy/0.4/valid_triplets_filtered.pkl
test_triplets: ../data/datasets/wv_squarelin/triplets/align=0.84_noisy/0.4/test_triplets_filtered.pkl
weights:
- 1
- 0
- 1
- 1
powers:
- 2
- 2
filtered: true
