wandb_project: wv_squarelin_noisy
wandb_group: align=0.84_p=0.3_filtered
train_triplets: ../datasets/wv_squarelin_triplets/align=0.84_noisy/0.3/train_triplets_filtered.pkl
valid_triplets: ../datasets/wv_squarelin_triplets/align=0.84_noisy/0.3/valid_triplets_filtered.pkl
test_triplets: ../datasets/wv_squarelin_triplets/align=0.84_noisy/0.3/test_triplets_filtered.pkl
weights:
- 1
- 0
- 1
- 1
powers:
- 2
- 2
filtered: true
