wandb_mode: online
wandb_project: wv_3d_linear_unfiltered
wandb_group: align=1
train_triplets: ../datasets/wv_3d_linear_triplets/align=1/train_triplets.pkl
valid_triplets: ../datasets/wv_3d_linear_triplets/align=1/valid_triplets.pkl
test_triplets: ../datasets/wv_3d_linear_triplets/align=1/test_triplets.pkl
weights:
- 1
- 1
- 0
- 0
powers:
- 2
- 2
filtered: false
out_csv: wv_3d_linear.csv
