wandb_project: wv_linear_sm_num
wandb_group: align=0.92_p=0.015625
train_triplets: ../data/datasets/wv_linear_sm_triplets/align=0.92_num/0.015625/train_triplets.pkl
valid_triplets: ../data/datasets/wv_linear_sm_triplets/align=0.92_num/0.015625/valid_triplets.pkl
test_triplets: ../data/datasets/wv_linear_sm_triplets/align=0.92_num/0.015625/test_triplets.pkl
weights:
- 1
- 1
- 1
- 1
powers:
- 2
- 2
filtered: false
model: MTL_slow
