wandb_project: wv_linear_sm_aligns
wandb_group: align=0.92
train_triplets: ..//net/scratch/tianh/explain_teach/data/datasets/wv_linear_sm/triplets/align=0.92/train_triplets.pkl
valid_triplets: ..//net/scratch/tianh/explain_teach/data/datasets/wv_linear_sm/triplets/align=0.92/valid_triplets.pkl
test_triplets: ..//net/scratch/tianh/explain_teach/data/datasets/wv_linear_sm/triplets/align=0.92/test_triplets.pkl
weights:
- 1
- 1
- 1
- 1
powers:
- 2
- 2
filtered: false
