wandb_project: wv_syn_bm_aligns
wandb_group: align=0.69_filtered
train_triplets: ../datasets/wv_syn_bm_triplets/align=0.69/train_triplets_filtered.pkl
valid_triplets: ../datasets/wv_syn_bm_triplets/align=0.69/valid_triplets_filtered.pkl
test_triplets: ../datasets/wv_syn_bm_triplets/align=0.69/test_triplets_filtered.pkl
weights:
- 0
- 1
- 1
- 1
powers:
- 2
- 2
filtered: true
