wandb_mode: online
wandb_project: wv_3d_linear_num_filtered
wandb_group: align=0.8_p=0.25
train_triplets: ../datasets/wv_3d_linear/triplets/align=0.8_num/0.25/train_triplets_filtered.pkl
valid_triplets: ../datasets/wv_3d_linear/triplets/align=0.8_num/0.25/valid_triplets_filtered.pkl
test_triplets: ../datasets/wv_3d_linear/triplets/align=0.8_num/0.25/test_triplets_filtered.pkl
weights:
- 64
- 1
- 64
- 64
powers:
- 2
- 2
