wandb_project: wv_squarelin_aligns
wandb_group: align=0.56_filtered
train_triplets: ../data/datasets/wv_squarelin_triplets/align=0.56/train_triplets_filtered.pkl
valid_triplets: ../data/datasets/wv_squarelin_triplets/align=0.56/valid_triplets_filtered.pkl
test_triplets: ../data/datasets/wv_squarelin_triplets/align=0.56/test_triplets_filtered.pkl
weights:
- 0
- 1
- 1
- 1
powers:
- 2
- 2
filtered: true
