wandb_project: wv_squarelin_aligns
wandb_group: align=0.99_filtered
train_triplets: ../datasets/wv_squarelin_triplets/align=0.99/train_triplets_filtered.pkl
valid_triplets: ../datasets/wv_squarelin_triplets/align=0.99/valid_triplets_filtered.pkl
test_triplets: ../datasets/wv_squarelin_triplets/align=0.99/test_triplets_filtered.pkl
weights:
- 32
- 256
- 1
- 1
powers:
- 2
- 2
filtered: true
