wandb_project: wv_syn_bm_aligns
wandb_group: align=0.97
train_triplets: ../datasets/wv_syn_bm_triplets/align=0.97/train_triplets.pkl
valid_triplets: ../datasets/wv_syn_bm_triplets/align=0.97/valid_triplets.pkl
test_triplets: ../datasets/wv_syn_bm_triplets/align=0.97/test_triplets.pkl
weights:
- 32
- 32
- 1
- 1
powers:
- 2
- 2
filtered: false
