wandb_mode: online
wandb_project: wv_3d_square_noisy
wandb_group: align=0.925_p=0.8
train_triplets: ../datasets/wv_3d_square_triplets/align=0.925_noisy/0.8/train_triplets.pkl
valid_triplets: ../datasets/wv_3d_square_triplets/align=0.925_noisy/0.8/valid_triplets.pkl
test_triplets: ../datasets/wv_3d_square_triplets/align=0.925_noisy/0.8/test_triplets.pkl
weights:
- 256
- 1
- 256
- 256
powers:
- 2
- 2
filtered: False
max_epochs: 3