wandb_mode: online
wandb_project: wv_3d_square_num
wandb_group: align=0.8_p=0.125
train_triplets: ../data/datasets/wv_3d_square_triplets/align=0.8_num/0.125/train_triplets.pkl
valid_triplets: ../data/datasets/wv_3d_square_triplets/align=0.8_num/0.125/valid_triplets.pkl
test_triplets: ../data/datasets/wv_3d_square_triplets/align=0.8_num/0.125/test_triplets.pkl
weights:
- 1
- 0
- 1
- 1
powers:
- 2
- 2
model: MTL_slow
filtered: False
