### classification data
train_dir : ../datasets/wv_3d_linear0/train
valid_dir : ../datasets/wv_3d_linear0/valid
test_dir : ../datasets/wv_3d_linear0/test
num_class : 2
transform : wv_3d

syn: true
train_synthetic: ../datasets/wv_3d_linear0/train_features.pkl
valid_synthetic: ../datasets/wv_3d_linear0/valid_features.pkl
test_synthetic: ../datasets/wv_3d_linear0/test_features.pkl

deterministic: true
aug: false

embeds_output_dir : /net/scratch/tianh/explain_teach/embeds
resn_embed_dir: wv_3d_linear0_RESN
predicted_labels: True
