wandb_mode: online
wandb_project: wv_3d_linear_num
wandb_group: align=0.97_p=0.03125
train_triplets: ../data/datasets/wv_3d_linear_triplets/align=0.97_num/0.03125/train_triplets_filtered.pkl
valid_triplets: ../data/datasets/wv_3d_linear_triplets/align=0.97_num/0.03125/valid_triplets_filtered.pkl
test_triplets: ../data/datasets/wv_3d_linear_triplets/align=0.97_num/0.03125/test_triplets_filtered.pkl
weights:
- 128
- 1
- 0
- 0
powers:
- 2
- 2
filtered: true
