wandb_project: wv_3d_linear0_noisy
wandb_group: align=0.9_p=0.1_filtered
train_triplets: ../datasets/wv_3d_linear0_triplets/align=0.9_noisy/0.1/train_triplets_filtered.pkl
valid_triplets: ../datasets/wv_3d_linear0_triplets/align=0.9_noisy/0.1/valid_triplets_filtered.pkl
test_triplets: ../datasets/wv_3d_linear0_triplets/align=0.9_noisy/0.1/test_triplets_filtered.pkl
weights:
- 1
- 1000000
- 1
- 1
powers:
- 2
- 2
filtered: true
