wandb_project: wv_linear_sm_noisy
wandb_group: align=0.82_p=0.2
train_triplets: ../datasets/wv_linear_sm_triplets/align=0.82_noisy/0.2/train_triplets.pkl
valid_triplets: ../datasets/wv_linear_sm_triplets/align=0.82_noisy/0.2/valid_triplets.pkl
test_triplets: ../datasets/wv_linear_sm_triplets/align=0.82_noisy/0.2/test_triplets.pkl
weights:
- 0
- 1
- 1
- 1
powers:
- 2
- 2
filtered: false
