### Wandb args
wandb_mode : online
wandb_project: wv_2d
wandb_group: align=0.7

#### synthetic data
syn: True
train_synthetic : ../embeds/wv_2d/train.pkl
valid_synthetic : ../embeds/wv_2d/valid.pkl
test_synthetic : ../embeds/wv_2d/test.pkl

### triplet data
<<<<<<< HEAD:models/configs/wv_2d/temp/align=0.7.yaml
train_triplets: ../datasets/wv_2d_triplets/align=0.7/train_triplets.pkl
valid_triplets: ../datasets/wv_2d_triplets/align=0.7/valid_triplets.pkl
test_triplets: ../datasets/wv_2d_triplets/align=0.7/test_triplets.pkl
=======
train_triplets: ../dataset/wv_2d_triplets/align=0.7/train_triplets.pkl
valid_triplets: ../dataset/wv_2d_triplets/align=0.7/valid_triplets.pkl
test_triplets: ../dataset/wv_2d_triplets/align=0.7/test_triplets.pkl
>>>>>>> d3cac975d7958e9356b73ca8e0f7e1eee5347815:models/configs/wv_2d/triplets/align=0.7.yaml
weights: 
  - 1
  - 0
powers:
  - 2
  - 2


### overwrite args
embed_dim : 50