wandb_mode: online
wandb_project:  wv_3d_square_num_filtered
wandb_group: align=0.925_p=0.25
train_triplets: ../datasets/wv_3d_square_triplets/align=0.925_num/0.25/train_triplets_filtered.pkl
valid_triplets: ../datasets/wv_3d_square_triplets/align=0.925_num/0.25/valid_triplets_filtered.pkl
test_triplets: ../datasets/wv_3d_square_triplets/align=0.925_num/0.25/test_triplets_filtered.pkl
weights:
- 256
- 1
- 256
- 256
powers:
- 2
- 2
model: MTL_slow
filtered: True
