### classification data
train_dir : ../datasets/wv_3d_blob_2/train
valid_dir : ../datasets/wv_3d_blob_2/valid
test_dir : ../datasets/wv_3d_blob_2/test
num_class : 2
transform : wv_3d

syn: true
train_synthetic: ../datasets/wv_3d_blob_2/train_features.pkl
valid_synthetic: ../datasets/wv_3d_blob_2/valid_features.pkl
test_synthetic: ../datasets/wv_3d_blob_2/test_features.pkl

deterministic: true
aug: false

embeds_output_dir : /net/scratch/tianh/explain_teach/embeds
resn_embed_dir: wv_3d_blob_2_RESN
predicted_labels: True
