wandb_mode: online
wandb_project: wv_3d
wandb_group: align=0.83_filtered
train_triplets: ../datasets/wv_3d_triplets/align=0.83/train_triplets_filtered.pkl
valid_triplets: ../datasets/wv_3d_triplets/align=0.83/valid_triplets_filtered.pkl
test_triplets: ../datasets/wv_3d_triplets/align=0.83/test_triplets_filtered.pkl
weights:
- 0
- 1
- 1
- 1
powers:
- 2
- 2
embed_dim: 50
