wandb_mode: online
wandb_project: wv_3d
wandb_group: align=0.92
train_triplets: ../datasets/wv_3d_triplets/align=0.92/train_triplets.pkl
valid_triplets: ../datasets/wv_3d_triplets/align=0.92/valid_triplets.pkl
test_triplets: ../datasets/wv_3d_triplets/align=0.92/test_triplets.pkl
weights:
- 1
- 256
- 256
- 256
powers:
- 2
- 2
embed_dim: 50
