wandb_mode: online
wandb_project: wv_3d_alignments
wandb_group: align=0.6
train_triplets: ../datasets/wv_3d_triplets/align=0.6/train_triplets.pkl
valid_triplets: ../datasets/wv_3d_triplets/align=0.6/valid_triplets.pkl
test_triplets: ../datasets/wv_3d_triplets/align=0.6/test_triplets.pkl
weights:
- 9.61e-06
- 0
- 1
- 1
powers:
- 2
- 2
embed_dim: 50
