wandb_mode: online
wandb_project: wv_3d_linear_noisy
wandb_group: align=0.97_p=0.2
train_triplets: ../datasets/wv_3d_linear_triplets/align=0.97_noisy/0.2/train_triplets_filtered.pkl
valid_triplets: ../datasets/wv_3d_linear_triplets/align=0.97_noisy/0.2/valid_triplets_filtered.pkl
test_triplets: ../datasets/wv_3d_linear_triplets/align=0.97_noisy/0.2/test_triplets_filtered.pkl
weights:
- 128
- 1
- 0
- 0
powers:
- 2
- 2
filtered: true
out_csv: wv_3d_linear_noisy.csv
