wandb_mode: online
wandb_project: wv_3d_linear_unfiltered
wandb_group: align=0.97
train_triplets: ../datasets/wv_3d_linear_triplets/align=0.97/train_triplets.pkl
valid_triplets: ../datasets/wv_3d_linear_triplets/align=0.97/valid_triplets.pkl
test_triplets: ../datasets/wv_3d_linear_triplets/align=0.97/test_triplets.pkl
weights:
- 128
- 1
- 0
- 0
powers:
- 2
- 2
filtered: false
out_csv: wv_3d_blob.csv
