wandb_project: wv_3d_blob_aligns
wandb_group: align=1
train_triplets: ../datasets/wv_3d_blob_triplets/align=1/train_triplets_filtered.pkl
valid_triplets: ../datasets/wv_3d_blob_triplets/align=1/valid_triplets_filtered.pkl
test_triplets: ../datasets/wv_3d_blob_triplets/align=1/test_triplets_filtered.pkl
weights:
- 1
- 1
- 0
- 0
powers:
- 2
- 2
filtered: true
