### classification data
train_dir : ../datasets/wv_3d/train
valid_dir : ../datasets/wv_3d/valid
test_dir : ../datasets/wv_3d/test
num_class : 2
transform : wv_3d

syn: true
train_synthetic: ../datasets/wv_3d/train_features.pkl
valid_synthetic: ../datasets/wv_3d/valid_features.pkl
test_synthetic: ../datasets/wv_3d/test_features.pkl

deterministic: true
aug: false

embeds_output_dir : /net/scratch/tianh/explain_teach/embeds
