### classification data
train_dir : /net/scratch/tianh-shared/wv_3d/2feats/auto_split/train
valid_dir : /net/scratch/tianh-shared/wv_3d/2feats/auto_split/valid
test_dir : /net/scratch/tianh-shared/wv_3d/2feats/auto_split/test
num_class : 2
transform : wv
train_batch_size : 64

### synthetic data
syn: True
train_synthetic : /net/scratch/tianh-shared/wv_3d/2feats/auto_split/train.pkl
test_synthetic : /net/scratch/tianh-shared/wv_3d/2feats/auto_split/test.pkl