### Training args
do_train : False
do_test: True

### Hyperparameters
embed_dim : 50
learning_rate : 1e-4
train_batch_size : 30
triplet_batch_size : 60
pretrained: true


max_epochs : 1
wandb_mode: disabled
checkpoint_callback: False
deterministic: True
ckpt_path: /data/hanliu/explain_teach/models/SLQ4Wt4P4HnwVSaEpGzBHd/checkpoints/epoch=0-step=133.ckpt
embeds_output_dir: None