### Training args
do_train : True
do_test: True

### Hyperparameters
learning_rate : 1e-4
train_batch_size : 30
triplet_batch_size : 40
pretrained: true
deterministic: True
check_val_every_n_epoch: 1
enable_progress_bar: False





max_epochs : 3
embed_dim : 50
checkpoint_callback: False
embeds_output_dir: ../embeds
# wandb_project : wv_3d_d=512
# wandb_group : RESN_d=512
out_csv : wv_3d_linear.csv