### Training args
do_train : True
do_test: True

### Hyperparameters
embed_dim : 50
learning_rate : 1e-4
train_batch_size : 30
triplet_batch_size : 40
pretrained: true
deterministic: True
# ckpt_path: /data/hanliu/explain_teach/models/SLQ4Wt4P4HnwVSaEpGzBHd/checkpoints/epoch=0-step=133.ckpt
check_val_every_n_epoch: 1
enable_progress_bar: False





max_epochs : 1
checkpoint_callback: False
# embeds_output_dir: ../embeds
k: 1
wandb_group : test