wandb_mode: online
wandb_project: wv_3d_linear_num
wandb_group: align=0.8_p=0.5
train_triplets: ../datasets/wv_3d_linear/triplets/align=0.8_num/0.5/train_triplets.pkl
valid_triplets: ../datasets/wv_3d_linear/triplets/align=0.8_num/0.5/valid_triplets.pkl
test_triplets: ../datasets/wv_3d_linear/triplets/align=0.8_num/0.5/test_triplets.pkl
weights:
- 64
- 1
- 64
- 64
powers:
- 2
- 2
