wandb_project: wv_linear_sm_aligns
wandb_group: align=0.85_filtered
train_triplets: ../datasets/wv_linear_sm_triplets/align=0.85/train_triplets_filtered.pkl
valid_triplets: ../datasets/wv_linear_sm_triplets/align=0.85/valid_triplets_filtered.pkl
test_triplets: ../datasets/wv_linear_sm_triplets/align=0.85/test_triplets_filtered.pkl
weights:
- 1
- 0
- 0
- 0
powers:
- 2
- 2
filtered: true
