wandb_project: wv_linear_sm_aligns
wandb_group: align=0.77_filtered
train_triplets: ../datasets/wv_linear_sm_triplets/align=0.77/train_triplets_filtered.pkl
valid_triplets: ../datasets/wv_linear_sm_triplets/align=0.77/valid_triplets_filtered.pkl
test_triplets: ../datasets/wv_linear_sm_triplets/align=0.77/test_triplets_filtered.pkl
weights:
- 0
- 32
- 1
- 1
powers:
- 2
- 2
filtered: true
