wandb_project: wv_linear_sm_aligns
wandb_group: align=94_filtered
train_triplets: ../data/datasets/wv_linear_sm_triplets/align=94/train_triplets_filtered.pkl
valid_triplets: ../data/datasets/wv_linear_sm_triplets/align=94/valid_triplets_filtered.pkl
test_triplets: ../data/datasets/wv_linear_sm_triplets/align=94/test_triplets_filtered.pkl
weights:
- 32
- 128
- 1
- 1
powers:
- 2
- 2
filtered: true
