wandb_project: wv_squarelin_noisy
wandb_group: align=0.84_p=0.1
train_triplets: ../data/datasets/wv_squarelin_triplets/align=0.84_noisy/0.1/train_triplets.pkl
valid_triplets: ../data/datasets/wv_squarelin_triplets/align=0.84_noisy/0.1/valid_triplets.pkl
test_triplets: ../data/datasets/wv_squarelin_triplets/align=0.84_noisy/0.1/test_triplets.pkl
weights:
- 1
- 0
- 1
- 1
powers:
- 2
- 2
filtered: false
