### Training args
dataloader_num_workers: 16
gpus: 1
seed: 42
do_train : True
do_test : True

### Wandb args
wandb_mode : online
wandb_entity: ai-driven-tutorial
wandb_group: None
wandb_project : None
wandb_name : None
