### classification data
train_dir : ../data/datasets/bm/train
valid_dir : ../data/datasets/bm/valid
test_dir : ../data/datasets/bm/test
num_class : 2
transform : bird
train_batch_size: 120

dataset: bm