wandb_mode : online

### Training args
do_train : True
do_test: True

### Hyperparameters
learning_rate : 1e-4
train_batch_size : 30
triplet_batch_size : 40
pretrained: true
deterministic: True
check_val_every_n_epoch: 1
enable_progress_bar: False


checkpoint_callback: False
wandb_entity : harry-tian


filter: True
embeds_output_dir : bm_lpips


max_epochs: 10

