wandb_project: wv_linear_sm_noisy
wandb_group: align=0.92_p=0.1
train_triplets: ../data/datasets/wv_linear_sm_triplets/align=0.92_noisy/0.1/train_triplets.pkl
valid_triplets: ../data/datasets/wv_linear_sm_triplets/align=0.92_noisy/0.1/valid_triplets.pkl
test_triplets: ../data/datasets/wv_linear_sm_triplets/align=0.92_noisy/0.1/test_triplets.pkl
weights:
- 1
- 1
- 1
- 1
powers:
- 2
- 2
filtered: false
