### classification data
train_dir : ../data/datasets/wv_syn_bm/train
valid_dir : ../data/datasets/wv_syn_bm/valid
test_dir : ../data/datasets/wv_syn_bm/test
num_class : 2
transform : wv_3d

syn: true
train_synthetic: ../data/datasets/wv_syn_bm/train_features.pkl
valid_synthetic: ../data/datasets/wv_syn_bm/valid_features.pkl
test_synthetic: ../data/datasets/wv_syn_bm/test_features.pkl

deterministic: true
aug: false

embeds_output_dir : /net/scratch/tianh/explain_teach/embeds
resn_embed_dir: wv_syn_bm_RESN
