wandb_mode: online
wandb_project: wv_3d_linear_num
wandb_group: align=0.97_p=0.03125
train_triplets: ../datasets/wv_3d_linear_triplets/align=0.97_num/0.03125/train_triplets.pkl
valid_triplets: ../datasets/wv_3d_linear_triplets/align=0.97_num/0.03125/valid_triplets.pkl
test_triplets: ../datasets/wv_3d_linear_triplets/align=0.97_num/0.03125/test_triplets.pkl
weights:
- 128
- 1
- 0
- 0
powers:
- 2
- 2
filtered: false
