wandb_mode: online
wandb_project: wv_3d_linear_aligns
wandb_group: align=0.85
train_triplets: ../datasets/wv_3d_linear_triplets/align=0.85/train_triplets.pkl
valid_triplets: ../datasets/wv_3d_linear_triplets/align=0.85/valid_triplets.pkl
test_triplets: ../datasets/wv_3d_linear_triplets/align=0.85/test_triplets.pkl
weights:
- 1
- 0
- 1
- 1
powers:
- 2
- 2
embed_dim: 50
