wandb_mode: online
wandb_project: wv_3d_linear_aligns
wandb_group: align=0.985_filtered
train_triplets: ../datasets/wv_3d_linear_triplets/align=0.985/train_triplets_filtered.pkl
valid_triplets: ../datasets/wv_3d_linear_triplets/align=0.985/valid_triplets_filtered.pkl
test_triplets: ../datasets/wv_3d_linear_triplets/align=0.985/test_triplets_filtered.pkl
weights:
- 1
- 1
- 0
- 0
powers:
- 2
- 2
embed_dim: 50
