wandb_mode: online
wandb_project: wv_3d_linear0_num
wandb_group: align=0.97_p=0.5
train_triplets: ../datasets/wv_3d_linear0_triplets/align=0.97_num/0.5/train_triplets_filtered.pkl
valid_triplets: ../datasets/wv_3d_linear0_triplets/align=0.97_num/0.5/valid_triplets_filtered.pkl
test_triplets: ../datasets/wv_3d_linear0_triplets/align=0.97_num/0.5/test_triplets_filtered.pkl
weights:
- 128
- 1
- 0
- 0
powers:
- 2
- 2
filtered: true
