wandb_mode: online
wandb_project: wv_3d_linear0_num
wandb_group: align=0.97_p=0.015625
train_triplets: ../datasets/wv_3d_linear0_triplets/align=0.97_num/0.015625/train_triplets.pkl
valid_triplets: ../datasets/wv_3d_linear0_triplets/align=0.97_num/0.015625/valid_triplets.pkl
test_triplets: ../datasets/wv_3d_linear0_triplets/align=0.97_num/0.015625/test_triplets.pkl
weights:
- 128
- 1
- 0
- 0
powers:
- 2
- 2
filtered: false
