### Wandb args
wandb_mode : online
wandb_project: wv_2d
wandb_group: align=0.7_pretrained_filtered

#### synthetic data
syn: True
train_synthetic : ../embeds/wv_2d/train.pkl
test_synthetic : ../embeds/wv_2d/test.pkl

### triplet data
train_triplets: ../data/wv_2d_triplets/align=0.7/train_triplets_filtered.pkl
valid_triplets: ../data/wv_2d_triplets/align=0.7/valid_triplets_filtered.pkl
test_triplets: ../data/wv_2d_triplets/align=0.7/test_triplets_filtered.pkl
weights: 
  - 1
  - 0
powers:
  - 2
  - 2


### overwrite args
embed_dim : 50
pretrained: true