wandb_mode: online
wandb_project: wv_2d
wandb_group: align=0.975
syn: true
train_synthetic: ../embeds/wv_2d/train.pkl
valid_synthetic: ../embeds/wv_2d/valid.pkl
test_synthetic: ../embeds/wv_2d/test.pkl
train_triplets: ../dataset/wv_2d_triplets/align=0.975/train_triplets.pkl
valid_triplets: ../dataset/wv_2d_triplets/align=0.975/valid_triplets.pkl
test_triplets: ../dataset/wv_2d_triplets/align=0.975/test_triplets.pkl
weights:
- 1
- 0.5
powers:
- 2
- 2
embed_dim: 50
