### Wandb args
wandb_mode : online
wandb_project: wv_2d
wandb_group : TN_test
wandb_name : w1=0_w2=1

#### synthetic data
syn: True
train_synthetic : ../embeds/wv_2d/train.pkl
test_synthetic : ../embeds/wv_2d/test.pkl

### triplet data
train_triplets: ../data/wv_2d_triplets/w1=1_w2=0/train_triplets.pkl
valid_triplets: ../data/wv_2d_triplets/w1=1_w2=0/valid_triplets.pkl
test_triplets: ../data/wv_2d_triplets/w1=1_w2=0/test_triplets.pkl
weights: 
  - 0
  - 1
powers:
  - 2
  - 2