### Wandb args
wandb_mode : online
wandb_project: wv_2d
wandb_group: w1=1_w2=0_pretrained

#### synthetic data
syn: True
train_synthetic : /net/scratch/tianh/explain_teach/embeds/wv_2d/train.pkl
test_synthetic : /net/scratch/tianh/explain_teach/embeds/wv_2d/test.pkl

### triplet data
train_triplets: /net/scratch/tianh/explain_teach/data/wv_2d_triplets/w1=1_w2=0/train_triplets.pkl
valid_triplets: /net/scratch/tianh/explain_teach/data/wv_2d_triplets/w1=1_w2=0/valid_triplets.pkl
test_triplets: /net/scratch/tianh/explain_teach/data/wv_2d_triplets/w1=1_w2=0/test_triplets.pkl
weights: 
  - 1
  - 0
powers:
  - 2
  - 2


### overwrite args
embed_dim : 50
max_epochs: 200
pretrained: true