### Wandb args
wandb_mode : online
wandb_project: wv_2d
wandb_group : RESN_test
wandb_name : w1=1_w2=1

#### synthetic data
syn: True
train_synthetic : ../embeds/wv_2d/train.pkl
test_synthetic : ../embeds/wv_2d/test.pkl

### triplet data
train_triplets: ../data/wv_2d_triplets/align=0.0/train_triplets_10000.pkl
valid_triplets: ../data/wv_2d_triplets/align=0.0/valid_triplets_10000.pkl
test_triplets: ../data/wv_2d_triplets/align=0.0/test_triplets_10000.pkl
weights: 
  - 1
  - 1 
powers:
  - 2
  - 2