
### synthetic data
syn: True
train_synthetic : ../embeds/wv_2d/train.pkl
test_synthetic : ../embeds/wv_2d/test.pkl




### triplet data
train_triplets : ../data/wv_2d_triplets/w1=10000_w2=1/train_triplets_10000.pkl
valid_triplets : ../data/wv_2d_triplets/w1=10000_w2=1/valid_triplets_10000.pkl
test_triplets : ../data/wv_2d_triplets/w1=10000_w2=1/test_triplets_10000.pkl


weights: 
  - 10000
  - 1 