### Wandb args
syn: False

### synthetic data
# syn: True
# train_synthetic : ../embeds/wv_3d/train.pkl
# test_synthetic : ../embeds/wv_3d/test.pkl
### triplet data
train_triplets: ../data/wv_triplets/align=0.0/train_triplets_10000.pkl
valid_triplets: ../data/wv_triplets/align=0.0/valid_triplets_10000.pkl
test_triplets: ../data/wv_triplets/align=0.0/test_triplets_10000.pkl
weights: 
  - 2.7303
  - 1 
powers:
  - 2
  - 2