### classification data
train_dir : ../datasets/wv_squarelin/train
valid_dir : ../datasets/wv_squarelin/valid
test_dir : ../datasets/wv_squarelin/test
num_class : 2
transform : wv_3d

syn: true
train_synthetic: ../datasets/wv_squarelin/train_features.pkl
valid_synthetic: ../datasets/wv_squarelin/valid_features.pkl
test_synthetic: ../datasets/wv_squarelin/test_features.pkl

deterministic: true
aug: false

embeds_output_dir : /net/scratch/tianh/explain_teach/embeds
resn_embed_dir: wv_squarelin_RESN
