wandb_mode: online
wandb_project: wv_3d_linear_num
wandb_group: align=0.62_p=0.125
train_triplets: ../data/datasets/wv_3d_linear_triplets/align=0.62_num/0.125/train_triplets.pkl
valid_triplets: ../data/datasets/wv_3d_linear_triplets/align=0.62_num/0.125/valid_triplets.pkl
test_triplets: ../data/datasets/wv_3d_linear_triplets/align=0.62_num/0.125/test_triplets.pkl
weights:
- 0
- 1
- 0
- 0
powers:
- 2
- 2
filtered: false
out_csv: wv_3d_linear_num.csv
