wandb_project: wv_linear_sm_noisy
wandb_group: align=0.92_p=0.2_filtered
train_triplets: ../data/datasets/wv_linear_sm_triplets/align=0.92_noisy/0.2/train_triplets_filtered.pkl
valid_triplets: ../data/datasets/wv_linear_sm_triplets/align=0.92_noisy/0.2/valid_triplets_filtered.pkl
test_triplets: ../data/datasets/wv_linear_sm_triplets/align=0.92_noisy/0.2/test_triplets_filtered.pkl
weights:
- 1
- 1
- 1
- 1
powers:
- 2
- 2
filtered: true
