wandb_mode: online
wandb_project: wv_3d_linear_noisy
wandb_group: align=0.85_p=0.05
train_triplets: ../datasets/wv_3d_linear_triplets/align=0.85_noisy/0.05/train_triplets.pkl
valid_triplets: ../datasets/wv_3d_linear_triplets/align=0.85_noisy/0.05/valid_triplets.pkl
test_triplets: ../datasets/wv_3d_linear_triplets/align=0.85_noisy/0.05/test_triplets.pkl
weights:
- 1
- 0
- 1
- 1
powers:
- 2
- 2
embed_dim: 50
