wandb_mode: online
wandb_project: wv_3d_noisy
wandb_group: align=0.8_p=0.1
train_triplets: ../datasets/wv_3d_square_triplets/align=0.8_noisy/0.1/train_triplets.pkl
valid_triplets: ../datasets/wv_3d_square_triplets/align=0.8_noisy/0.1/valid_triplets.pkl
test_triplets: ../datasets/wv_3d_square_triplets/align=0.8_noisy/0.1/test_triplets.pkl
weights:
- 1
- 0
- 1
- 1
powers:
- 2
- 2
embed_dim: 50
