wandb_project: wv_squarelin_noisy
wandb_group: align=0.95_p=0.7
train_triplets: ../data/datasets/wv_squarelin_triplets/align=0.95_noisy/0.7/train_triplets.pkl
valid_triplets: ../data/datasets/wv_squarelin_triplets/align=0.95_noisy/0.7/valid_triplets.pkl
test_triplets: ../data/datasets/wv_squarelin_triplets/align=0.95_noisy/0.7/test_triplets.pkl
weights:
- 1
- 1
- 1
- 1
powers:
- 2
- 2
filtered: false
