wandb_mode: online
wandb_project: wv_3d_linear_noisy_filtered
wandb_group: align=0.63_p=0.15
train_triplets: ../datasets/wv_3d_linear/triplets/align=0.63_noisy/0.15/train_triplets.pkl
valid_triplets: ../datasets/wv_3d_linear/triplets/align=0.63_noisy/0.15/valid_triplets.pkl
test_triplets: ../datasets/wv_3d_linear/triplets/align=0.63_noisy/0.15/test_triplets.pkl
weights:
- 1
- 0
- 1
- 1
powers:
- 2
- 2
