wandb_project: wv_linear_mm_aligns
wandb_group: align=0.97
train_triplets: /net/scratch/tianh/explain_teach/data/datasets/wv_linear_mm/triplets/align=0.97/train_triplets.pkl
valid_triplets: /net/scratch/tianh/explain_teach/data/datasets/wv_linear_mm/triplets/align=0.97/valid_triplets.pkl
test_triplets: /net/scratch/tianh/explain_teach/data/datasets/wv_linear_mm/triplets/align=0.97/test_triplets.pkl
weights:
- 100
- 10000000
- 1
- 1
powers:
- 2
- 2
