wandb_project: wv_linear_sm_noisy
wandb_group: align=0.82_p=0.7_filtered
train_triplets: ../datasets/wv_linear_sm_triplets/align=0.82_noisy/0.7/train_triplets_filtered.pkl
valid_triplets: ../datasets/wv_linear_sm_triplets/align=0.82_noisy/0.7/valid_triplets_filtered.pkl
test_triplets: ../datasets/wv_linear_sm_triplets/align=0.82_noisy/0.7/test_triplets_filtered.pkl
weights:
- 0
- 1
- 1
- 1
powers:
- 2
- 2
filtered: true
