wandb_mode: online
wandb_project: wv_3d_square_aligns
wandb_group: align=0.5
train_triplets: ../data/datasets/wv_3d_square_triplets/align=0.5/train_triplets.pkl
valid_triplets: ../data/datasets/wv_3d_square_triplets/align=0.5/valid_triplets.pkl
test_triplets: ../data/datasets/wv_3d_square_triplets/align=0.5/test_triplets.pkl
weights:
- 0
- 0
- 1
- 1
powers:
- 2
- 2
filtered: False
