### Wandb args
wandb_mode : online
wandb_project: wv_2d_alignments_alignments
wandb_group: align=0.7

#### synthetic data
syn: True
train_synthetic : ../embeds/wv_2d/train.pkl
valid_synthetic : ../embeds/wv_2d/valid.pkl
test_synthetic : ../embeds/wv_2d/test.pkl

### triplet data
train_triplets: ../datasets/wv_2d_triplets/align=0.7/train_triplets.pkl
valid_triplets: ../datasets/wv_2d_triplets/align=0.7/valid_triplets.pkl
test_triplets: ../datasets/wv_2d_triplets/align=0.7/test_triplets.pkl
weights: 
  - 1
  - 0
powers:
  - 2
  - 2


### overwrite args
embed_dim : 50