wandb_mode: online
wandb_project: wv_2d_filtered
wandb_group: align=0.85_filtered
syn: true
train_synthetic: ../data/embeds/wv_2d/train.pkl
valid_synthetic: ../data/embeds/wv_2d/valid.pkl
test_synthetic: ../data/embeds/wv_2d/test.pkl
train_triplets: ../data/datasets/wv_2d_triplets/align=0.85/train_triplets_filtered.pkl
valid_triplets: ../data/datasets/wv_2d_triplets/align=0.85/valid_triplets_filtered.pkl
test_triplets: ../data/datasets/wv_2d_triplets/align=0.85/test_triplets_filtered.pkl
weights:
- 1
- 0.0025
powers:
- 2
- 2
embed_dim: 50
