model: MTL

### Wandb args
wandb_group : MTL0.5
wandb_name : MTL0.5

### Training args
do_train : True
do_test: True

### Hyperparameters
embed_dim : 50
max_epochs : 50
learning_rate : 1e-4
train_batch_size : 60
triplet_batch_size : 200
lamda : 0.5
pretrained: true
