model: MTL

### Wandb args
wandb_group : MTL0.2
wandb_name :  MTL0.2

### Training args
do_train : True
do_test: True

### Hyperparameters
embed_dim : 50
max_epochs : 100
learning_rate : 1e-4
train_batch_size : 60
triplet_batch_size : 200
lamda : 0.2
pretrained: true
