### classification data
<<<<<<< HEAD
train_dir : ../datasets/weevil_vespula/train
valid_dir : ../datasets/weevil_vespula/valid
test_dir : ../datasets/weevil_vespula/test
=======
train_dir : ../dataset/weevil_vespula/train
valid_dir : ../dataset/weevil_vespula/valid
test_dir : ../dataset/weevil_vespula/test
>>>>>>> d3cac975d7958e9356b73ca8e0f7e1eee5347815
num_class : 2
transform : wv
