### classification data
train_dir : ../datasets/weevil_vespula/train
valid_dir : ../datasets/weevil_vespula/valid
test_dir : ../datasets/weevil_vespula/test
num_class : 2
transform : wv

deterministic: true
aug: false

embeds_output_dir : /net/scratch/tianh/explain_teach/embeds
