### classification data
train_dir : /net/scratch/chacha-shared/weevil_vespula/train
valid_dir : /net/scratch/chacha-shared/weevil_vespula/valid
test_dir : /net/scratch/chacha-shared/weevil_vespula/test
num_class : 2
transform : wv
train_batch_size : 196
