### Wandb args
wandb_mode : online
wandb_project : wv
wandb_group : test
wandb_name : RESN

### Training args
do_train : True
do_test: True

### Hyperparameters
embed_dim : 10
max_epochs : 50
learning_rate : 1e-4
train_batch_size : 120
lamda : 0.5
pretrained: False
