### Wandb args
wandb_mode : online
wandb_project: wv_2d
wandb_group : MTl_test
wandb_name : w1=0_w2=1

### Training args
do_train : True
do_test: True

### Hyperparameters
embed_dim : 10
max_epochs : 100
learning_rate : 1e-4
train_batch_size : 32
lamda : 0.5
pretrained: False
