### triplet data
train_triplets : /net/scratch/tianh/explain_teach/data/wv_triplets/w1=10000_w2=1/train_triplets_10000.pkl
valid_triplets : /net/scratch/tianh/explain_teach/data/wv_triplets/w1=10000_w2=1/valid_triplets_10000.pkl
test_triplets : /net/scratch/tianh/explain_teach/data/wv_triplets/w1=10000_w2=1/test_triplets_10000.pkl


weights: 
  - 10000
  - 1 