### Wandb args
wandb_project : wv
wandb_group : w1=2.7303

### triplet data
train_triplets : /net/scratch/tianh/explain_teach/data/wv_triplets/w1=2.7303_w2=1/train_triplets_10000.pkl
valid_triplets : /net/scratch/tianh/explain_teach/data/wv_triplets/w1=2.7303_w2=1/valid_triplets_10000.pkl
test_triplets : /net/scratch/tianh/explain_teach/data/wv_triplets/w1=2.7303_w2=1/test_triplets_10k.pkl
weights: 
  - 2.7303
  - 1 
