wandb_project: wv_3d_linear0_aligns
wandb_group: align=0.82_filtered
train_triplets: ../datasets/wv_3d_linear0_triplets/align=0.82/train_triplets_filtered.pkl
valid_triplets: ../datasets/wv_3d_linear0_triplets/align=0.82/valid_triplets_filtered.pkl
test_triplets: ../datasets/wv_3d_linear0_triplets/align=0.82/test_triplets_filtered.pkl
weights:
- 0
- 1000
- 1
- 1
powers:
- 2
- 2
filtered: true
