wandb_project: wv_3d_linear0_aligns
wandb_group: align=0.97_filtered
train_triplets: ../data/datasets/wv_3d_linear0_triplets/align=0.97/train_triplets_filtered.pkl
valid_triplets: ../data/datasets/wv_3d_linear0_triplets/align=0.97/valid_triplets_filtered.pkl
test_triplets: ../data/datasets/wv_3d_linear0_triplets/align=0.97/test_triplets_filtered.pkl
weights:
- 1
- 100
- 0
- 0
powers:
- 2
- 2
filtered: true
