wandb_mode: online
wandb_project: wv_3d_square_noisy_filtered
wandb_group: align=0.925_p=0.5
train_triplets: ../data/datasets/wv_3d_square_triplets/align=0.925_noisy/0.5/train_triplets_filtered.pkl
valid_triplets: ../data/datasets/wv_3d_square_triplets/align=0.925_noisy/0.5/valid_triplets_filtered.pkl
test_triplets: ../data/datasets/wv_3d_square_triplets/align=0.925_noisy/0.5/test_triplets_filtered.pkl
weights:
- 256
- 1
- 256
- 256
powers:
- 2
- 2
max_epochs: 3
