wandb_mode: online
wandb_project: wv_3d_square_aligns
wandb_group: align=0.83_filtered
train_triplets: ../data/datasets/wv_3d_square_triplets/align=0.83/train_triplets_filtered.pkl
valid_triplets: ../data/datasets/wv_3d_square_triplets/align=0.83/valid_triplets_filtered.pkl
test_triplets: ../data/datasets/wv_3d_square_triplets/align=0.83/test_triplets_filtered.pkl
weights:
- 0
- 1
- 1
- 1
powers:
- 2
- 2
filtered: True
