wandb_mode: online
wandb_project: wv_3d_blob_noisy
wandb_group: align=0.62_p=0.1
train_triplets: ../datasets/wv_3d_blob_triplets/align=0.62_noisy/0.1/train_triplets_filtered.pkl
valid_triplets: ../datasets/wv_3d_blob_triplets/align=0.62_noisy/0.1/valid_triplets_filtered.pkl
test_triplets: ../datasets/wv_3d_blob_triplets/align=0.62_noisy/0.1/test_triplets_filtered.pkl
weights:
- 0
- 1
- 0
- 0
powers:
- 2
- 2
filtered: true
out_csv: wv_3d_blob_noisy.csv
