wandb_project: wv_3d_blob_aligns
wandb_group: align=0.985
train_triplets: ../datasets/wv_3d_blob_triplets/align=0.985/train_triplets.pkl
valid_triplets: ../datasets/wv_3d_blob_triplets/align=0.985/valid_triplets.pkl
test_triplets: ../datasets/wv_3d_blob_triplets/align=0.985/test_triplets.pkl
weights:
- 1
- 0
- 0
- 0
powers:
- 2
- 2
filtered: false
