wandb_mode: online
wandb_project: wv_3d_linear_noisy
wandb_group: align=0.97_p=0.5
train_triplets: ../data/datasets/wv_3d_linear_triplets/align=0.97_noisy/0.5/train_triplets.pkl
valid_triplets: ../data/datasets/wv_3d_linear_triplets/align=0.97_noisy/0.5/valid_triplets.pkl
test_triplets: ../data/datasets/wv_3d_linear_triplets/align=0.97_noisy/0.5/test_triplets.pkl
weights:
- 128
- 1
- 0
- 0
powers:
- 2
- 2
filtered: false
out_csv: wv_3d_linear_noisy.csv
