wandb_mode: online
wandb_project: wv_3d_linear
wandb_group: align=1
train_triplets: ../data/datasets/wv_3d_linear_triplets/align=1/train_triplets_filtered.pkl
valid_triplets: ../data/datasets/wv_3d_linear_triplets/align=1/valid_triplets_filtered.pkl
test_triplets: ../data/datasets/wv_3d_linear_triplets/align=1/test_triplets_filtered.pkl
weights:
- 1
- 1
- 0
- 0
powers:
- 2
- 2
filtered: true
out_csv: wv_3d_linear.csv
