wandb_project: wv_3d_linear0_aligns
wandb_group: align=0.75
train_triplets: ../data/datasets/wv_3d_linear0_triplets/align=0.75/train_triplets.pkl
valid_triplets: ../data/datasets/wv_3d_linear0_triplets/align=0.75/valid_triplets.pkl
test_triplets: ../data/datasets/wv_3d_linear0_triplets/align=0.75/test_triplets.pkl
weights:
- 1
- 100000
- 0
- 0
powers:
- 2
- 2
filtered: false
