wandb_project: wv_3d_linear0_aligns
wandb_group: align=0.97
train_triplets: ../datasets/wv_3d_linear0_triplets/align=0.97/train_triplets.pkl
valid_triplets: ../datasets/wv_3d_linear0_triplets/align=0.97/valid_triplets.pkl
test_triplets: ../datasets/wv_3d_linear0_triplets/align=0.97/test_triplets.pkl
weights:
- 1
- 100
- 0
- 0
powers:
- 2
- 2
filtered: false
