wandb_project: wv_squarelin_num
wandb_group: align=0.95_p=0.5_filtered
train_triplets: ../data/datasets/wv_squarelin_triplets/align=0.95_num/0.5/train_triplets_filtered.pkl
valid_triplets: ../data/datasets/wv_squarelin_triplets/align=0.95_num/0.5/valid_triplets_filtered.pkl
test_triplets: ../data/datasets/wv_squarelin_triplets/align=0.95_num/0.5/test_triplets_filtered.pkl
weights:
- 1
- 1
- 1
- 1
powers:
- 2
- 2
filtered: true
model: MTL_slow
