wandb_project: wv_linear_sm_aligns
wandb_group: align=94
train_triplets: ../datasets/wv_linear_sm_triplets/align=94/train_triplets.pkl
valid_triplets: ../datasets/wv_linear_sm_triplets/align=94/valid_triplets.pkl
test_triplets: ../datasets/wv_linear_sm_triplets/align=94/test_triplets.pkl
weights:
- 32
- 128
- 1
- 1
powers:
- 2
- 2
filtered: false
