wandb_project: wv_linear_sm_aligns
wandb_group: align=0.9
train_triplets: ../datasets/wv_linear_sm_triplets/align=0.9/train_triplets.pkl
valid_triplets: ../datasets/wv_linear_sm_triplets/align=0.9/valid_triplets.pkl
test_triplets: ../datasets/wv_linear_sm_triplets/align=0.9/test_triplets.pkl
weights:
- 1
- 512
- 0
- 0
powers:
- 2
- 2
filtered: false
