wandb_project: wv_linear_sm_aligns
wandb_group: align=0.76
train_triplets: ../datasets/wv_linear_sm_triplets/align=0.76/train_triplets.pkl
valid_triplets: ../datasets/wv_linear_sm_triplets/align=0.76/valid_triplets.pkl
test_triplets: ../datasets/wv_linear_sm_triplets/align=0.76/test_triplets.pkl
weights:
- 0
- 1
- 0
- 0
powers:
- 2
- 2
filtered: false
