model_path: MTL
model: RESN

### Wandb args
wandb_group : RESN
wandb_name : RESN

### Training args
do_train : True
do_test: True

### Hyperparameters
embed_dim : 50
max_epochs : 80
learning_rate : 1e-4
train_batch_size : 30
triplet_batch_size : 200
lamda : 1
pretrained: True
