model_path: MTL
model: RESN

### Wandb args
wandb_project : resnet18

### Training args
do_train : True
do_test: True

### Hyperparameters
embed_dim : 50
learning_rate : 1e-4
train_batch_size: 30


max_epochs : 5
