wandb_mode: online
wandb_project: wv_3d_linear_unfiltered
wandb_group: align=0.95
train_triplets: ../datasets/wv_3d_linear/triplets/align=0.95/train_triplets.pkl
valid_triplets: ../datasets/wv_3d_linear/triplets/align=0.95/valid_triplets.pkl
test_triplets: ../datasets/wv_3d_linear/triplets/align=0.95/test_triplets.pkl
weights:
- 1
- 1
- 1
- 1
powers:
- 2
- 2
