wandb_mode: online
wandb_project: wv_3d_square_misc
wandb_group: inclass_align=0.92
train_triplets: ../data/datasets/wv_3d_square_triplets/align=0.92/train_triplets_inclass.pkl
valid_triplets: ../data/datasets/wv_3d_square_triplets/align=0.92/valid_triplets_inclass.pkl
test_triplets: ../data/datasets/wv_3d_square_triplets/align=0.92/test_triplets_inclass.pkl
weights:
- 1
- 256
- 256
- 256
powers:
- 2
- 2
filtered: False
