wandb_mode: online
wandb_project: wv_3d_linear_num_triplets
wandb_group: align=0.1255_p=0.125
train_triplets: ../datasets/wv_3d_linear_triplets/align=0.1255_num/0.125/train_triplets.pkl
valid_triplets: ../datasets/wv_3d_linear_triplets/align=0.1255_num/0.125/valid_triplets.pkl
test_triplets: ../datasets/wv_3d_linear_triplets/align=0.1255_num/0.125/test_triplets.pkl
weights:
- 0
- 1
- 1
- 1
powers:
- 2
- 2
embed_dim: 50
