dataloader_num_workers: 16
gpus: 1
#seed: 42
do_train: true
do_test: true
wandb_mode: online
wandb_entity: ai-driven-tutorial
wandb_project: wv
wandb_group: RESN
wandb_name: align=0
embed_dim: 10
max_epochs: 50
learning_rate: 0.0001
train_batch_size: 64
lamda: 0.5
pretrained: False
train_dir: /net/scratch/tianh-shared/wv_3d/pseudo_label/auto_split/train
valid_dir: /net/scratch/tianh-shared/wv_3d/pseudo_label/auto_split/valid
test_dir: /net/scratch/tianh-shared/wv_3d/pseudo_label/auto_split/test
num_class: 2
transform: wv
syn: true
train_synthetic: /net/scratch/tianh-shared/wv_3d/pseudo_label/auto_split/train.pkl
test_synthetic: /net/scratch/tianh-shared/wv_3d/pseudo_label/auto_split/test.pkl
train_triplets: ../data/wv_triplets/align=0.0/train_triplets_10000.pkl
valid_triplets: ../data/wv_triplets/align=0.0/valid_triplets_10000.pkl
test_triplets: ../data/wv_triplets/align=0.0/test_triplets_10000.pkl
weights:
- -30
- 121
- 963
- -844
powers:
- 1
- 2
- -2
- -2
