### Wandb args
wandb_mode : online
wandb_project : baselines
wandb_group : bird
wandb_name : RESN_pretrained

### Training args
do_train : True
do_test: True

### Hyperparameters
embed_dim : 10
max_epochs : 50
learning_rate : 1e-4
train_batch_size : 120
lamda : 0.5
pretrained: True
