### Wandb args
wandb_mode: online
wandb_project : bm_prolific
wandb_group : MTL_0.5
wandb_name : bs_120_200

### Training args
do_train : True
do_test: True

### Hyperparameters
embed_dim : 10
max_epochs : 100
learning_rate : 1e-4
train_batch_size : 120
triplet_batch_size : 200
lamda : 0.5
pretrained: False
