### Wandb args
wandb_mode : disabled
wandb_project: bm_prolific
wandb_group: MTLT0.5
wandb_name: b120e100

### Training args
do_train : True
do_test: True

### Hyperparameters
max_epochs : 100
learning_rate : 1e-4
train_batch_size : 120
log_every_n_steps: 10
lamda : 0.5
pretrained: False
deterministic: True