### Wandb args
wandb_mode : online
wandb_project: bm_prolific
wandb_group : MTLT0.5

### Training args
do_train : True
do_test: True

### Hyperparameters
max_epochs : 100
learning_rate : 1e-4
train_batch_size : 120
lamda : 0.5
pretrained: False
