### Wandb args
wandb_project : bm_prolific
wandb_group : baselines
wandb_name : TN

### Training args
do_train : True
do_test: True

### Hyperparameters
embed_dim : 10
max_epochs : 200
learning_rate : 5e-3
train_batch_size : 64
lamda : 0.2
pretrained: False
