### Wandb args

### triplet data
train_triplets : /net/scratch/tianh/explain_teach/data/bm_triplets/train_triplets.pkl
valid_triplets : /net/scratch/tianh/explain_teach/data/bm_triplets/valid_triplets.pkl
test_triplets : /net/scratch/tianh/explain_teach/data/bm_triplets/test_triplets.pkl


train_batch_size : 32
lamda : 0.2
max_epochs : 100
pretrained: false

transform : resn