### Wandb args
wandb_project : bm_prolific
wandb_group : TN_cosdropout
wandb_name : bs=50

### triplet data
train_triplets : /net/scratch/tianh/explain_teach/data/bm_triplets/train_triplets.pkl
valid_triplets : /net/scratch/tianh/explain_teach/data/bm_triplets/valid_triplets.pkl
test_triplets : /net/scratch/tianh/explain_teach/data/bm_triplets/test_triplets.pkl


train_batch_size : 50
lamda : 0.2
max_epochs : 400
pretrained: false

transform : resn