### Wandb args

### triplet data
train_triplets : ../data/bm_triplets/train_triplets.pkl
valid_triplets : ../data/bm_triplets/valid_triplets.pkl
test_triplets : ../data/bm_triplets/test_triplets.pkl
dataloader_num_workers: 16