wandb_project: wv_squarelin_num
wandb_group: align=0.84_p=0.03125
train_triplets: ../data/datasets/wv_squarelin/triplets/align=0.84_num/0.03125/train_triplets.pkl
valid_triplets: ../data/datasets/wv_squarelin/triplets/align=0.84_num/0.03125/valid_triplets.pkl
test_triplets: ../data/datasets/wv_squarelin/triplets/align=0.84_num/0.03125/test_triplets.pkl
weights:
- 1
- 0
- 1
- 1
powers:
- 2
- 2
filtered: false
model: MTL_slow
