### Wandb args
wandb_mode: online
wandb_project : bm_filtered_d512_e50
wandb_group : pre_no_aug_2

### triplet data
train_triplets : ../datasets/bm_prolific_triplets/train_triplets_filtered.pkl
valid_triplets : ../datasets/bm_prolific_triplets/valid_triplets_filtered.pkl
test_triplets : ../datasets/bm_prolific_triplets/test_triplets.pkl

### overwrite args
dataloader_num_workers: 4
embed_dim: 512
max_epochs: 50
pretrained: True
aug: False
deterministic: True
embeds_output_dir: ../embeds/bm/prolific