### Wandb args
wandb_mode: online
wandb_project : lpips
wandb_group : bm 

### triplet data
train_triplets : ../data/triplets/bm/lpips/train_triplets.pkl
valid_triplets : ../data/triplets/bm/lpips/valid_triplets.pkl
test_triplets : ../data/triplets/bm/lpips/test_triplets.pkl

### overwrite args
dataloader_num_workers: 4
embed_dim: 50
max_epochs: 50
pretrained: True
embeds_output_dir: ../data/embeds/lpips/bm