### Wandb args
wandb_mode: online
wandb_project : bm_prolific_d50_e50
wandb_group : pre_no_aug_0

### triplet data
train_triplets : ../datasets/bm_prolific_triplets/train_triplets.pkl
valid_triplets : ../datasets/bm_prolific_triplets/valid_triplets.pkl
test_triplets : ../datasets/bm_prolific_triplets/test_triplets.pkl

### overwrite args
dataloader_num_workers: 4
embed_dim: 50
max_epochs: 50
pretrained: True
aug: False
embeds_output_dir: ../embeds/bm/prolific