### Wandb args
wandb_mode : offline
wandb_project: wv_3d
wandb_group: RESN

#### synthetic data
syn: True
train_synthetic : ../datasets/wv_3d/train.pkl
valid_synthetic : ../datasets/wv_3d/valid.pkl
test_synthetic : ../datasets/wv_3d/test.pkl

### triplet data
train_triplets: ../datasets/wv_3d_triplets/align=1/train_triplets.pkl
valid_triplets: ../datasets/wv_3d_triplets/align=1/valid_triplets.pkl
test_triplets: ../datasets/wv_3d_triplets/align=1/test_triplets.pkl
weights: 
  - 1
  - 0
powers:
  - 2
  - 2


### overwrite args
embed_dim : 50
deterministic: true