wandb_project: wv_squarelin_noisy
wandb_group: align=0.95_p=0.6_filtered
train_triplets: ../data/datasets/wv_squarelin/triplets/align=0.95_noisy/0.6/train_triplets_filtered.pkl
valid_triplets: ../data/datasets/wv_squarelin/triplets/align=0.95_noisy/0.6/valid_triplets_filtered.pkl
test_triplets: ../data/datasets/wv_squarelin/triplets/align=0.95_noisy/0.6/test_triplets_filtered.pkl
weights:
- 1
- 1
- 1
- 1
powers:
- 2
- 2
filtered: true
