wandb_mode: online
wandb_project: wv_3d_alignments_filtered
wandb_group: align=0.8
train_triplets: ../datasets/wv_3d_triplets/align=0.8/train_triplets_filtered.pkl
valid_triplets: ../datasets/wv_3d_triplets/align=0.8/valid_triplets_filtered.pkl
test_triplets: ../datasets/wv_3d_triplets/align=0.8/test_triplets_filtered.pkl
weights:
- 1
- 0
- 1
- 1
powers:
- 2
- 2
embed_dim: 50
