wandb_mode: online
wandb_project: wv_3d_filtered
wandb_group: align=1_filtered
syn: true
train_synthetic: ../datasets/wv_3d/train.pkl
valid_synthetic: ../datasets/wv_3d/valid.pkl
test_synthetic: ../datasets/wv_3d/test.pkl
train_triplets: ../datasets/wv_3d_triplets/align=1/train_triplets_filtered.pkl
valid_triplets: ../datasets/wv_3d_triplets/align=1/valid_triplets_filtered.pkl
test_triplets: ../datasets/wv_3d_triplets/align=1/test_triplets_filtered.pkl
weights:
- 1
- 1
powers:
- 2
- 2
embed_dim: 50
