### Wandb args
wandb_mode : online
wandb_project: wv_3d_filtered
wandb_group: align=0.7_filtered

#### synthetic data
syn: True
train_synthetic : ../datasets/wv_3d/train.pkl
valid_synthetic : ../datasets/wv_3d/valid.pkl
test_synthetic : ../datasets/wv_3d/test.pkl

### triplet data
train_triplets: ../datasets/wv_3d_triplets/align=0.7/train_triplets_filtered.pkl
valid_triplets: ../datasets/wv_3d_triplets/align=0.7/valid_triplets_filtered.pkl
test_triplets: ../datasets/wv_3d_triplets/align=0.7/test_triplets_filtered.pkl
weights: 
  - 1
  - 0
powers:
  - 2
  - 2


### overwrite args
embed_dim : 50