### Training args
do_train : True
do_test: True

### Hyperparameters
learning_rate : 1e-4
train_batch_size : 30
triplet_batch_size : 40
pretrained: true
deterministic: True
check_val_every_n_epoch: 1
enable_progress_bar: False



predicted_labels: True

max_epochs : 3
embed_dim : 512
checkpoint_callback: False
embeds_output_dir: ../embeds

wandb_entity : harry-tian
wandb_project: wv_3d_square_predicted_filtered
out_csv : wv_3d_square_MTL_predicted_filtered.csv