### classification data
train_dir : /net/scratch/tianh-shared/chest_xray/train
valid_dir : /net/scratch/tianh-shared/chest_xray/valid
test_dir : /net/scratch/tianh-shared/chest_xray/test
num_class : 3
transform : resn
train_batch_size : 120

### synthetic data
syn: False