### Wandb args
wandb_mode : online
wandb_project : chest_xray
wandb_group : test
wandb_name : lr=bs=64_1e-4

### Training args
do_train : True
do_test: True

### Hyperparameters
embed_dim : 10
max_epochs : 200
learning_rate : 1e-4
train_batch_size : 64
lamda : 0.5
pretrained: True
