### Wandb args
# 
# wandb_group : w1=2.7303

### triplet data
train_triplets : /net/scratch/tianh/explain_teach/data/wv_triplets/align=1/train_triplets_10000.pkl
valid_triplets : /net/scratch/tianh/explain_teach/data/wv_triplets/align=1/valid_triplets_10000.pkl
test_triplets : /net/scratch/tianh/explain_teach/data/wv_triplets/align=1/test_triplets_10k.pkl