wandb_project: wv_squarelin_aligns
wandb_group: align=0.95
train_triplets: ../data/datasets/wv_squarelin/triplets/align=0.95/train_triplets.pkl
valid_triplets: ../data/datasets/wv_squarelin/triplets/align=0.95/valid_triplets.pkl
test_triplets: ../data/datasets/wv_squarelin/triplets/align=0.95/test_triplets.pkl
weights:
- 1
- 1
- 1
- 1
powers:
- 2
- 2
filtered: false
