wandb_project: wv_squarelin_aligns
wandb_group: align=0.56
train_triplets: ../datasets/wv_squarelin_triplets/align=0.56/train_triplets.pkl
valid_triplets: ../datasets/wv_squarelin_triplets/align=0.56/valid_triplets.pkl
test_triplets: ../datasets/wv_squarelin_triplets/align=0.56/test_triplets.pkl
weights:
- 0
- 1
- 1
- 1
powers:
- 2
- 2
filtered: false
