wandb_mode: online
wandb_project: wv_3d_linear_num_filtered
wandb_group: align=0.63_p=0.1
train_triplets: ../datasets/wv_3d_linear/triplets/align=0.63_num/0.1/train_triplets_filtered.pkl
valid_triplets: ../datasets/wv_3d_linear/triplets/align=0.63_num/0.1/valid_triplets_filtered.pkl
test_triplets: ../datasets/wv_3d_linear/triplets/align=0.63_num/0.1/test_triplets_filtered.pkl
weights:
- 1
- 0
- 1
- 1
powers:
- 2
- 2
