wandb_project: wv_3d_linear0_num
wandb_group: align=0.9_p=0.0078125_filtered
train_triplets: ../datasets/wv_3d_linear0_triplets/align=0.9_num/0.0078125/train_triplets_filtered.pkl
valid_triplets: ../datasets/wv_3d_linear0_triplets/align=0.9_num/0.0078125/valid_triplets_filtered.pkl
test_triplets: ../datasets/wv_3d_linear0_triplets/align=0.9_num/0.0078125/test_triplets_filtered.pkl
weights:
- 1
- 1000000
- 1
- 1
powers:
- 2
- 2
filtered: true
model: MTL_slow
